//! Arguments for local and remote cache lifecycle commands.

use std::path::PathBuf;

use clap::{Args, Subcommand};

#[derive(Debug, Args)]
pub struct CacheArgs {
    #[command(subcommand)]
    pub command: CacheCommand,
}

#[derive(Debug, Subcommand)]
pub enum CacheCommand {
    /// Print the active cache directory.
    Dir,

    /// Show cache size and mirror counts.
    Status,

    /// Verify project records and Git mirror object databases.
    Verify {
        /// Run full Git object verification instead of connectivity checks.
        #[arg(long)]
        full: bool,
    },

    /// Report or remove unreferenced cache entries.
    Gc {
        /// Minimum age of unreferenced entries.
        #[arg(long, default_value_t = 30, value_name = "DAYS")]
        max_age_days: u64,

        /// Delete reported entries.
        #[arg(long)]
        apply: bool,
    },

    /// Inspect and collect Lake's trace-keyed artifact store.
    Artifacts {
        #[command(subcommand)]
        command: ArtifactCacheCommand,
    },

    /// Push and pull authenticated Lake artifact snapshots.
    Remote {
        #[command(subcommand)]
        command: RemoteCacheCommand,
    },
}

#[derive(Debug, Subcommand)]
pub enum ArtifactCacheCommand {
    /// Show artifact, mapping, hard-link, and orphan counts.
    Status {
        /// Limit inspection to one Lean toolchain.
        #[arg(long, value_name = "TOOLCHAIN")]
        toolchain: Option<String>,

        /// Print machine-readable JSON.
        #[arg(long)]
        json: bool,
    },

    /// Validate mappings and check that local outputs exist.
    Verify {
        /// Limit verification to one Lean toolchain.
        #[arg(long, value_name = "TOOLCHAIN")]
        toolchain: Option<String>,

        /// Print machine-readable JSON.
        #[arg(long)]
        json: bool,
    },

    /// Report or remove unreferenced Lake artifacts.
    Gc {
        /// Limit collection to one Lean toolchain.
        #[arg(long, value_name = "TOOLCHAIN")]
        toolchain: Option<String>,

        /// Minimum age of unreferenced artifacts.
        #[arg(long, default_value_t = 30, value_name = "DAYS")]
        max_age_days: u64,

        /// Delete reported artifacts.
        #[arg(long)]
        apply: bool,

        /// Print machine-readable JSON.
        #[arg(long)]
        json: bool,
    },
}

/// Identity and transport options shared by remote snapshot uploads/downloads.
#[derive(Debug, Args)]
pub struct RemoteSnapshotArgs {
    /// Remote hierarchy, such as `organization/project`.
    #[arg(long, default_value = "default", value_name = "NAME")]
    pub namespace: String,

    /// Snapshot revision. Defaults to the current project lock digest.
    #[arg(long, value_name = "REVISION")]
    pub revision: Option<String>,

    /// Lean toolchain. Defaults to the current project toolchain.
    #[arg(long, value_name = "TOOLCHAIN")]
    pub toolchain: Option<String>,

    /// Native artifact platform. Defaults to the current host.
    #[arg(long, value_name = "PLATFORM")]
    pub platform: Option<String>,

    /// Permit plain HTTP to a non-loopback server.
    #[arg(long)]
    pub allow_insecure_http: bool,

    /// Print machine-readable JSON.
    #[arg(long)]
    pub json: bool,
}

#[derive(Debug, Subcommand)]
pub enum RemoteCacheCommand {
    /// Generate an Ed25519 signing key and shareable public key.
    Keygen {
        /// Destination for the mode-0600 signing key.
        #[arg(long, value_name = "PATH")]
        private_key: PathBuf,

        /// Destination for the public verification key.
        #[arg(long, value_name = "PATH")]
        public_key: PathBuf,

        /// Replace an existing key pair.
        #[arg(long)]
        force: bool,
    },

    /// Sign and upload the selected toolchain's Lake artifact snapshot.
    Push {
        /// Directory, file:// URL, or HTTPS object-store base URL.
        #[arg(value_name = "REMOTE")]
        remote: String,

        /// Ed25519 private key generated by `lev cache remote keygen`.
        #[arg(long, value_name = "PATH")]
        signing_key: PathBuf,

        #[command(flatten)]
        snapshot: RemoteSnapshotArgs,
    },

    /// Authenticate, verify, and install a Lake artifact snapshot.
    Pull {
        /// Directory, file:// URL, or HTTPS object-store base URL.
        #[arg(value_name = "REMOTE")]
        remote: String,

        /// Explicit Ed25519 public-key trust anchor.
        #[arg(long, value_name = "PATH")]
        public_key: PathBuf,

        #[command(flatten)]
        snapshot: RemoteSnapshotArgs,
    },
}
