//! Arguments for toolchain installation, storage, and publication.

use std::path::PathBuf;

use clap::{Args, Subcommand, ValueEnum};

#[derive(Debug, Args)]
pub struct ToolchainArgs {
    #[command(subcommand)]
    pub command: ToolchainCommand,
}

#[derive(Debug, Subcommand)]
pub enum ToolchainCommand {
    /// List toolchains installed in lev's store or optional elan.
    List {
        /// Measure each installed toolchain on disk.
        #[arg(long)]
        sizes: bool,
    },

    /// Install a toolchain if it is not already present.
    Install {
        /// Lean toolchain to install.
        #[arg(value_name = "TOOLCHAIN")]
        toolchain: String,

        /// Installation backend.
        #[arg(long, value_enum, default_value_t = ToolchainBackend::Auto)]
        backend: ToolchainBackend,

        /// Permit a direct download without an official SHA-256 digest.
        #[arg(long)]
        allow_unverified: bool,

        /// Signed chunk object-store base URL or directory.
        #[arg(long, value_name = "REMOTE")]
        remote: Option<String>,

        /// Public key used to authenticate a signed chunk manifest.
        #[arg(long, value_name = "PATH")]
        public_key: Option<PathBuf>,

        /// Permit plain HTTP to a non-loopback chunk server.
        #[arg(long)]
        allow_insecure_http: bool,

        /// Pin the current project to the installed toolchain.
        #[arg(long)]
        pin: bool,
    },

    /// Remove a lev-store installation or uninstall an elan-only toolchain.
    Remove {
        /// Lean toolchain to uninstall.
        #[arg(value_name = "TOOLCHAIN")]
        toolchain: String,
    },

    /// Print the installation path for a toolchain.
    Which {
        /// Lean toolchain to locate.
        #[arg(value_name = "TOOLCHAIN")]
        toolchain: String,
    },

    /// Import an installed toolchain into lev's content-addressed store.
    Import {
        /// Installed Lean toolchain to import.
        #[arg(value_name = "TOOLCHAIN")]
        toolchain: String,

        /// Pin the current project to the canonical imported toolchain name.
        #[arg(long)]
        pin: bool,
    },

    /// Inspect the content-addressed toolchain store.
    Store {
        #[command(subcommand)]
        command: ToolchainStoreCommand,
    },

    /// Publish or install signed content-defined toolchain chunks.
    Chunks {
        #[command(subcommand)]
        command: ToolchainChunksCommand,
    },

    /// Build or inspect a signed static toolchain CDN index.
    Index {
        #[command(subcommand)]
        command: ToolchainIndexCommand,
    },

    /// Report lev-store garbage and optional elan garbage.
    Gc {
        /// Delete unused toolchains instead of only reporting them.
        #[arg(long)]
        delete: bool,

        /// Emit a versioned report containing lev and optional elan results.
        #[arg(long)]
        json: bool,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum ToolchainBackend {
    /// Prefer a configured chunk remote, then verified direct downloads and elan.
    Auto,
    /// Install from an explicitly trusted signed chunk remote.
    Chunks,
    /// Download an official Lean release directly into lev's store.
    Direct,
    /// Delegate installation to elan.
    Elan,
}

#[derive(Debug, Subcommand)]
pub enum ToolchainChunksCommand {
    /// Chunk, sign, and publish an installed toolchain tree.
    Publish {
        /// Canonical Lean toolchain represented by the source tree.
        #[arg(value_name = "TOOLCHAIN")]
        toolchain: String,

        /// Directory, file:// URL, or HTTPS object-store base URL.
        #[arg(value_name = "REMOTE")]
        remote: String,

        /// Toolchain root. Defaults to the installed toolchain path.
        #[arg(long, value_name = "PATH")]
        source: Option<PathBuf>,

        /// Ed25519 private key generated by `lev cache remote keygen`.
        #[arg(long, value_name = "PATH")]
        signing_key: PathBuf,

        /// Native platform key. Defaults to the current host.
        #[arg(long, value_name = "PLATFORM")]
        platform: Option<String>,

        /// Permit plain HTTP to a non-loopback server.
        #[arg(long)]
        allow_insecure_http: bool,

        /// Print machine-readable JSON.
        #[arg(long)]
        json: bool,
    },

    /// Install a signed toolchain while reusing local files and chunks.
    Install {
        /// Canonical Lean toolchain requested from the signed manifest.
        #[arg(value_name = "TOOLCHAIN")]
        toolchain: String,

        /// Directory, file:// URL, or HTTPS object-store base URL.
        #[arg(value_name = "REMOTE")]
        remote: String,

        /// Explicit Ed25519 public-key trust anchor.
        #[arg(long, value_name = "PATH")]
        public_key: PathBuf,

        /// Native platform key. Defaults to the current host.
        #[arg(long, value_name = "PLATFORM")]
        platform: Option<String>,

        /// Permit plain HTTP to a non-loopback server.
        #[arg(long)]
        allow_insecure_http: bool,

        /// Pin the current project to the canonical installed toolchain name.
        #[arg(long)]
        pin: bool,

        /// Print machine-readable JSON.
        #[arg(long)]
        json: bool,
    },
}

#[derive(Debug, Subcommand)]
pub enum ToolchainIndexCommand {
    /// Verify published manifests and atomically rebuild the signed index.
    Build {
        /// Local static publication root containing toolchains-v1/manifests.
        #[arg(value_name = "DIRECTORY")]
        root: PathBuf,

        /// Ed25519 private key used to sign the index.
        #[arg(long, value_name = "PATH")]
        signing_key: PathBuf,

        /// Public key used to authenticate every included manifest.
        #[arg(long, value_name = "PATH")]
        public_key: PathBuf,

        /// Print machine-readable JSON.
        #[arg(long)]
        json: bool,
    },

    /// Authenticate and list entries from a local or HTTPS index.
    List {
        /// Directory, file:// URL, or HTTPS static-CDN base URL.
        #[arg(value_name = "REMOTE")]
        remote: String,

        /// Explicit Ed25519 public-key trust anchor.
        #[arg(long, value_name = "PATH")]
        public_key: PathBuf,

        /// Show only entries for this native platform key.
        #[arg(long, value_name = "PLATFORM")]
        platform: Option<String>,

        /// Permit plain HTTP to a non-loopback server.
        #[arg(long)]
        allow_insecure_http: bool,

        /// Print machine-readable JSON.
        #[arg(long)]
        json: bool,
    },

    /// Authenticate and validate a local or HTTPS index without listing it.
    Verify {
        /// Directory, file:// URL, or HTTPS static-CDN base URL.
        #[arg(value_name = "REMOTE")]
        remote: String,

        /// Explicit Ed25519 public-key trust anchor.
        #[arg(long, value_name = "PATH")]
        public_key: PathBuf,

        /// Permit plain HTTP to a non-loopback server.
        #[arg(long)]
        allow_insecure_http: bool,

        /// Print machine-readable JSON.
        #[arg(long)]
        json: bool,
    },
}

#[derive(Debug, Subcommand)]
pub enum ToolchainStoreCommand {
    /// Show logical size, object size, and deduplication savings.
    Status,

    /// Hash every object and verify every materialized toolchain view.
    Verify,

    /// Report or remove data not referenced by installed store manifests.
    Gc {
        /// Delete the reported manifests, views, and objects.
        #[arg(long)]
        apply: bool,
    },
}
