//! Deterministic base and multi-version dependency locks.
//!
//! Each entry binds an exact Lake manifest to project configuration, toolchain,
//! and platform. Resolution may come from Lake or lev's verified fast path.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};

use crate::cache::digest;
use crate::core::atomic_file::replace as atomic_write;
use crate::project::Project;
use crate::project::manifest::{LakeManifest, ManifestPackage};

const LOCK_VERSION: u32 = 2;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LevLock {
    version: u32,
    toolchain: String,
    platform: String,
    manifest_sha256: String,
    config_sha256: String,
    packages: Vec<LockedPackage>,

    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    environments: Vec<LockedEnvironment>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct LockedPackage {
    name: String,
    kind: String,
    direct: bool,

    #[serde(skip_serializing_if = "Option::is_none")]
    source: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    revision: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    requested: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    scope: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    subdir: Option<String>,
}

/// One complete Lake resolution for a toolchain and host platform.
///
/// The raw Lake JSON is stored with a normalized package summary. Validation
/// checks that they agree.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedEnvironment {
    toolchain: String,
    platform: String,
    policy_sha256: String,
    config_sha256: String,
    manifest_sha256: String,
    manifest: String,

    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    overrides: Vec<LockedOverride>,

    packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct LockedOverride {
    name: String,
    revision: String,
}

impl LevLock {
    pub fn generate(project: &Project) -> Result<Self> {
        let manifest_path = project.manifest_path();
        let manifest_bytes = fs::read(&manifest_path)
            .with_context(|| format!("failed to read {}", manifest_path.display()))?;
        let manifest: LakeManifest = serde_json::from_slice(&manifest_bytes)
            .with_context(|| format!("failed to parse {}", manifest_path.display()))?;
        let mut packages = manifest
            .packages
            .iter()
            .map(LockedPackage::from_manifest)
            .collect::<Vec<_>>();
        packages.sort_by(|left, right| {
            (&left.name, &left.kind, &left.source).cmp(&(&right.name, &right.kind, &right.source))
        });

        Ok(Self {
            version: LOCK_VERSION,
            toolchain: project.toolchain.clone(),
            platform: crate::core::platform::host_id(),
            manifest_sha256: digest(&manifest_bytes),
            config_sha256: project_config_digest(&project.root)?,
            packages,
            environments: Vec::new(),
        })
    }

    pub fn read(path: &Path) -> Result<Self> {
        let source = fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        let lock: Self = toml_edit::de::from_str(&source)
            .with_context(|| format!("failed to parse {}", path.display()))?;
        if lock.version != LOCK_VERSION {
            bail!(
                "{} uses unsupported lock version {}",
                path.display(),
                lock.version
            );
        }
        crate::core::platform::validate_id(&lock.platform)
            .with_context(|| format!("invalid base platform in {}", path.display()))?;
        lock.validate_environments(path)?;
        Ok(lock)
    }

    pub fn write(&self, path: &Path) -> Result<()> {
        let encoded =
            toml_edit::ser::to_string_pretty(self).context("failed to serialize lev.lock")?;
        let contents =
            format!("# This file is generated by lev. Commit it to version control.\n{encoded}");
        if fs::read(path).ok().as_deref() == Some(contents.as_bytes()) {
            return Ok(());
        }
        atomic_write(path, contents.as_bytes())
    }

    pub fn verify(project: &Project) -> Result<()> {
        let path = project.lock_path();
        if !path.is_file() {
            bail!("{} is missing; run `lev lock`", path.display());
        }
        let locked = Self::read(&path)?;
        let current = Self::generate(project)?;
        if locked.toolchain != current.toolchain {
            bail!(
                "{} was generated for {}, but lean-toolchain selects {}",
                path.display(),
                locked.toolchain,
                current.toolchain
            );
        }
        if locked.platform != current.platform {
            bail!(
                "{} was generated for platform {}, but this host is {}; run `lev lock`",
                path.display(),
                locked.platform,
                current.platform
            );
        }
        if locked.config_sha256 != current.config_sha256 {
            bail!(
                "Lake configuration changed since {}; run `lev lock`",
                path.display()
            );
        }
        if locked.manifest_sha256 != current.manifest_sha256 || locked.packages != current.packages
        {
            bail!(
                "lake-manifest.json changed since {}; run `lev lock`",
                path.display()
            );
        }
        Ok(())
    }

    fn validate_environments(&self, path: &Path) -> Result<()> {
        let mut previous: Option<(&str, &str)> = None;
        for environment in &self.environments {
            let identity = environment.identity();
            if previous.is_some_and(|value| value >= identity) {
                bail!(
                    "{} contains duplicate or unsorted environment identities",
                    path.display()
                );
            }
            environment
                .validate_internal()
                .with_context(|| format!("invalid {} environment", environment.toolchain))?;
            previous = Some(identity);
        }
        Ok(())
    }
}

impl LockedEnvironment {
    /// Capture the effective Lakefile and exact manifest produced by Lake.
    pub fn capture(
        project: &Project,
        policy_sha256: String,
        overrides: &BTreeMap<String, String>,
    ) -> Result<Self> {
        let manifest_path = project.manifest_path();
        let manifest_bytes = fs::read(&manifest_path)
            .with_context(|| format!("failed to read {}", manifest_path.display()))?;
        let manifest = String::from_utf8(manifest_bytes.clone())
            .with_context(|| format!("{} is not UTF-8", manifest_path.display()))?;
        let parsed: LakeManifest = serde_json::from_slice(&manifest_bytes)
            .with_context(|| format!("failed to parse {}", manifest_path.display()))?;
        let mut packages = parsed
            .packages
            .iter()
            .map(LockedPackage::from_manifest)
            .collect::<Vec<_>>();
        sort_packages(&mut packages);

        let environment = Self {
            toolchain: project.toolchain.clone(),
            platform: crate::core::platform::host_id(),
            policy_sha256,
            config_sha256: project_config_digest(&project.root)?,
            manifest_sha256: digest(&manifest_bytes),
            manifest,
            overrides: overrides
                .iter()
                .map(|(name, revision)| LockedOverride {
                    name: name.clone(),
                    revision: revision.clone(),
                })
                .collect(),
            packages,
        };
        environment.validate_internal()?;
        Ok(environment)
    }

    /// Canonical toolchain selected by this environment.
    pub fn toolchain(&self) -> &str {
        &self.toolchain
    }

    /// Native host identity captured with this resolution.
    pub fn platform(&self) -> &str {
        &self.platform
    }

    /// Stable content key used to isolate persistent build workspaces.
    pub fn workspace_key(&self) -> Result<String> {
        Ok(digest(&serde_json::to_vec(self)?))
    }

    /// Return the direct revision overlay in deterministic name order.
    pub fn overrides(&self) -> BTreeMap<String, String> {
        self.overrides
            .iter()
            .map(|entry| (entry.name.clone(), entry.revision.clone()))
            .collect()
    }

    /// Check that this entry matches the requested toolchain and policy.
    pub fn verify_policy(&self, toolchain: &str, policy_sha256: &str) -> Result<()> {
        self.validate_internal()?;
        if self.toolchain != toolchain {
            bail!(
                "environment was locked for {}, not {toolchain}",
                self.toolchain
            );
        }
        if self.policy_sha256 != policy_sha256 {
            bail!("environment policy changed for {toolchain}; run `lev lock --lean {toolchain}`");
        }
        Ok(())
    }

    /// Whether this environment is independent of its source checkout.
    pub(crate) fn is_resolution_cacheable(&self) -> Result<bool> {
        self.validate_internal()?;
        let manifest: LakeManifest =
            serde_json::from_str(&self.manifest).context("embedded Lake manifest is invalid")?;
        Ok(manifest.packages_dir == Path::new(".lake/packages")
            && manifest
                .packages
                .iter()
                .all(|package| package.kind == "git"))
    }

    /// Check the activated Lakefile and publish the embedded manifest.
    pub fn activate(&self, project: &Project) -> Result<()> {
        if project.toolchain != self.toolchain {
            bail!(
                "cannot activate {} in a {} workspace",
                self.toolchain,
                project.toolchain
            );
        }
        let host = crate::core::platform::host_id();
        if self.platform != host {
            bail!(
                "cannot activate {} environment for platform {} on {host}",
                self.toolchain,
                self.platform
            );
        }
        let config_sha256 = project_config_digest(&project.root)?;
        if config_sha256 != self.config_sha256 {
            bail!(
                "effective Lake configuration for {} does not match lev.lock",
                self.toolchain
            );
        }
        atomic_write(&project.manifest_path(), self.manifest.as_bytes())
    }

    fn validate_internal(&self) -> Result<()> {
        if self.toolchain.trim().is_empty()
            || self.toolchain.chars().any(char::is_whitespace)
            || self.policy_sha256.len() != 64
            || self.config_sha256.len() != 64
            || self.manifest_sha256.len() != 64
        {
            bail!("environment metadata is malformed");
        }
        crate::core::platform::validate_id(&self.platform)?;
        if digest(self.manifest.as_bytes()) != self.manifest_sha256 {
            bail!("embedded Lake manifest digest does not match");
        }
        let parsed: LakeManifest =
            serde_json::from_str(&self.manifest).context("embedded Lake manifest is invalid")?;
        let mut packages = parsed
            .packages
            .iter()
            .map(LockedPackage::from_manifest)
            .collect::<Vec<_>>();
        sort_packages(&mut packages);
        if packages != self.packages {
            bail!("embedded Lake manifest disagrees with its package inventory");
        }

        let mut previous: Option<&str> = None;
        for entry in &self.overrides {
            if entry.name.trim().is_empty()
                || entry.name.chars().any(char::is_whitespace)
                || entry.revision.trim().is_empty()
                || entry.revision.chars().any(char::is_whitespace)
            {
                bail!("environment dependency override is malformed");
            }
            if previous.is_some_and(|name| name >= entry.name.as_str()) {
                bail!("environment dependency overrides are duplicate or unsorted");
            }
            previous = Some(&entry.name);
        }
        Ok(())
    }

    fn identity(&self) -> (&str, &str) {
        (&self.toolchain, &self.platform)
    }
}

impl LockedPackage {
    fn from_manifest(package: &ManifestPackage) -> Self {
        let source = if package.kind == "path" {
            package
                .dir
                .as_ref()
                .map(|path| path.to_string_lossy().into_owned())
        } else {
            package.url.clone()
        };
        Self {
            name: package.name.clone(),
            kind: package.kind.clone(),
            direct: !package.inherited,
            source,
            revision: package.rev.clone(),
            requested: package.input_rev.clone(),
            scope: package.scope.clone().filter(|scope| !scope.is_empty()),
            subdir: package
                .sub_dir
                .as_ref()
                .map(|path| path.to_string_lossy().into_owned()),
        }
    }
}

fn sort_packages(packages: &mut [LockedPackage]) {
    packages.sort_by(|left, right| {
        (&left.name, &left.kind, &left.source).cmp(&(&right.name, &right.kind, &right.source))
    });
}

pub fn refresh(project: &Project) -> Result<()> {
    let path = project.lock_path();
    let environments = if path.is_file() {
        LevLock::read(&path)
            .map(|lock| lock.environments)
            .unwrap_or_default()
    } else {
        Vec::new()
    };
    let mut lock = LevLock::generate(project)?;
    lock.environments = environments;
    lock.write(&path)
}

pub fn verify(project: &Project) -> Result<()> {
    LevLock::verify(project)
}

/// Add or replace one toolchain environment without disturbing other locks.
pub fn upsert_environment(project: &Project, environment: LockedEnvironment) -> Result<()> {
    environment.validate_internal()?;
    let path = project.lock_path();
    let mut lock = LevLock::generate(project)?;
    if path.is_file() {
        lock.environments = LevLock::read(&path)?.environments;
    }
    match lock
        .environments
        .binary_search_by(|candidate| candidate.identity().cmp(&environment.identity()))
    {
        Ok(index) => lock.environments[index] = environment,
        Err(index) => lock.environments.insert(index, environment),
    }
    lock.write(&path)
}

/// Load and verify one version-specific environment from the project lock.
pub fn environment(
    project: &Project,
    toolchain: &str,
    policy_sha256: &str,
) -> Result<Option<LockedEnvironment>> {
    let path = project.lock_path();
    if !path.is_file() {
        return Ok(None);
    }
    let lock = LevLock::read(&path)?;
    let platform = crate::core::platform::host_id();
    let Some(environment) = lock
        .environments
        .iter()
        .find(|environment| environment.toolchain == toolchain && environment.platform == platform)
    else {
        return Ok(None);
    };
    environment.verify_policy(toolchain, policy_sha256)?;
    Ok(Some(environment.clone()))
}

pub(crate) fn project_config_digest(root: &Path) -> Result<String> {
    for name in ["lakefile.toml", "lakefile.lean"] {
        let path = root.join(name);
        if path.is_file() {
            let mut input = name.as_bytes().to_vec();
            input.push(0);
            input.extend(
                fs::read(&path).with_context(|| format!("failed to read {}", path.display()))?,
            );
            return Ok(digest(&input));
        }
    }
    bail!(
        "no lakefile.toml or lakefile.lean found in {}",
        root.display()
    )
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use std::collections::BTreeMap;

    use super::{LevLock, LockedEnvironment, environment, refresh, upsert_environment, verify};
    use crate::project::Project;

    #[test]
    fn writes_deterministic_lock_and_detects_changes() {
        let temp = tempdir().unwrap();
        fs::write(
            temp.path().join("lean-toolchain"),
            "leanprover/lean4:v4.fixture-d\n",
        )
        .unwrap();
        fs::write(
            temp.path().join("lakefile.toml"),
            "[package]\nname = \"demo\"\n",
        )
        .unwrap();
        fs::write(
            temp.path().join("lake-manifest.json"),
            r#"{
              "packagesDir": ".lake/packages",
              "packages": [
                {
                  "name": "solver",
                  "type": "git",
                  "url": "https://example.invalid/solver",
                  "rev": "0123456789abcdef0123456789abcdef01234567",
                  "inputRev": "release-d",
                  "inherited": false
                }
              ]
            }"#,
        )
        .unwrap();
        let project = Project::discover(temp.path()).unwrap();

        refresh(&project).unwrap();
        let first = fs::read_to_string(project.lock_path()).unwrap();
        refresh(&project).unwrap();
        assert_eq!(fs::read_to_string(project.lock_path()).unwrap(), first);
        assert_eq!(
            LevLock::read(&project.lock_path()).unwrap().packages.len(),
            1
        );
        verify(&project).unwrap();

        fs::write(
            temp.path().join("lakefile.toml"),
            "[package]\nname = \"changed\"\n",
        )
        .unwrap();
        assert!(
            verify(&project)
                .unwrap_err()
                .to_string()
                .contains("configuration changed")
        );
    }

    #[test]
    fn stores_exact_versioned_manifests_and_preserves_them_on_base_refresh() {
        let temp = tempdir().unwrap();
        fs::write(
            temp.path().join("lean-toolchain"),
            "leanprover/lean4:v4.fixture-d\n",
        )
        .unwrap();
        fs::write(
            temp.path().join("lakefile.toml"),
            "[package]\nname = \"demo\"\n",
        )
        .unwrap();
        fs::write(
            temp.path().join("lake-manifest.json"),
            r#"{"packagesDir":".lake/packages","packages":[],"name":"demo"}"#,
        )
        .unwrap();
        let source = Project::discover(temp.path()).unwrap();
        refresh(&source).unwrap();

        let resolved_root = temp.path().join("resolved");
        fs::create_dir(&resolved_root).unwrap();
        fs::write(
            resolved_root.join("lean-toolchain"),
            "leanprover/lean4:v4.fixture-c\n",
        )
        .unwrap();
        fs::write(
            resolved_root.join("lakefile.toml"),
            r#"
[package]
name = "demo"

[[require]]
name = "solver"
rev = "release-c"
"#,
        )
        .unwrap();
        let manifest = r#"{
          "packagesDir": ".lake/packages",
          "packages": [{
            "name": "solver",
            "type": "git",
            "url": "https://example.invalid/solver",
            "rev": "0123456789abcdef0123456789abcdef01234567",
            "inputRev": "release-c",
            "inherited": false
          }]
        }"#;
        fs::write(resolved_root.join("lake-manifest.json"), manifest).unwrap();
        let resolved = Project::load(resolved_root).unwrap();
        let policy = "a".repeat(64);
        let overrides = BTreeMap::from([("solver".to_owned(), "release-c".to_owned())]);
        let locked = LockedEnvironment::capture(&resolved, policy.clone(), &overrides).unwrap();
        let key = locked.workspace_key().unwrap();
        let mut foreign = locked.clone();
        foreign.platform = "test-os-test-arch".to_owned();
        upsert_environment(&source, foreign.clone()).unwrap();
        upsert_environment(&source, locked).unwrap();

        let loaded = environment(&source, &resolved.toolchain, &policy)
            .unwrap()
            .unwrap();
        assert_eq!(loaded.workspace_key().unwrap(), key);
        assert_eq!(loaded.overrides(), overrides);
        let stored = LevLock::read(&source.lock_path()).unwrap();
        assert_eq!(stored.environments.len(), 2);
        assert!(
            stored
                .environments
                .iter()
                .any(|entry| entry.platform == "test-os-test-arch")
        );
        let platform_error = foreign.activate(&resolved).unwrap_err().to_string();
        assert!(platform_error.contains("platform"), "{platform_error}");

        refresh(&source).unwrap();
        assert_eq!(
            LevLock::read(&source.lock_path())
                .unwrap()
                .environments
                .len(),
            2
        );
        assert!(
            environment(&source, &resolved.toolchain, &policy)
                .unwrap()
                .is_some()
        );

        fs::write(
            resolved.root.join("lakefile.toml"),
            "[package]\nname = \"wrong\"\n",
        )
        .unwrap();
        let error = loaded.activate(&resolved).unwrap_err().to_string();
        assert!(error.contains("does not match lev.lock"), "{error}");

        let error = environment(&source, &resolved.toolchain, &"b".repeat(64))
            .unwrap_err()
            .to_string();
        assert!(error.contains("policy changed"), "{error}");
    }
}
